### ISSUE TITLE
Add an option to hide media controls on Gnome notification panel

### ISSUE THREAD

**Issue by DodoLeDev** [qwreey75/quick-settings-tweaks#10]
#### Hi everyone!
I'm using this extension since Gnome 43 has been released for my distribution, and **I love it**! :heart_eyes:
There are so many useful options to customize my Quick Settings panel... It's AMAZING! :star_struck: 

**But I'm facing a little problem:**
When I enable the Media Control Widget, but not the Notification one, _I have duplicated MPRIS controls_!

| One in the Gnome Notification panel | And one in the Quick Settings panel |
|------------------------------------------|-----------------------------------------|
| ![image](https://user-images.githubusercontent.com/59477313/199534172-82fa1748-22a7-44a3-9d2a-b8203c27b6fe.png) | ![image](https://user-images.githubusercontent.com/59477313/199534298-7c591bab-2460-4726-b679-00a703dce4dd.png) |

### So could it be possible to add an option to hide media controls in the stock notifications panel, in order to only have the one in the Quick Settings panel?

**Comment by qwreey75** [comment]
![image](https://user-images.githubusercontent.com/46598063/199572251-fe9fb741-5dc1-40a3-80c1-bb61ddac7fd8.png)
Added feature! now we should check this feature have no bug and working well as we expected
