### ISSUE TITLE
Support for G45 version

### ISSUE THREAD

**Issue by gilvbp** [qwreey75/quick-settings-tweaks#100]
Hi, could you update the G45 version?
This tutorial might help:

 Here's the official link. https://gjs.guide/extensions/upgrading/gnome-shell-45.html#esm

PS: Here it's a link to an extension that's already working on G45 https://github.com/ionutbortis/gnome-bedtime-mode/tree/gnome45

**Comment by GerryT11** [comment]
FYI, here is some more information on the changes in Gnome 45 for extensions: https://blogs.gnome.org/shell-dev/2023/09/02/extensions-in-gnome-45/

**Comment by onlyreportingissues** [comment]
The Gnome devs offer additional help on their [Discourse](https://discourse.gnome.org/tag/extensions) and [Matrix](https://matrix.to/#/#extensions:gnome.org) channels, if needed.

**Comment by gilvbp** [comment]
https://github.com/qwreey75/quick-settings-tweaks/pull/103 already ported, thanks to @dapigguy
