### ISSUE TITLE
Gnome 45

### ISSUE THREAD

**Issue by evgnor86** [qwreey75/quick-settings-tweaks#109]
it's coming soon :)

**Comment by gmankab** [comment]
gnome 45 appeared in arch repos today

waiting for update :)

**Comment by qwreey75** [comment]
which distro supports 45 now? i didn't tested it now due to arch is not support 45 now

**Comment by freddyw** [comment]
Fedora has got the Beta version out. Apart from the extension mayhem, all seems to work very well.
https://fedoramagazine.org/announcing-fedora-39-beta/

**Comment by Bitals** [comment]
> which distro supports 45 now? i didn't tested it now due to arch is not support 45 now

Arch actually already did at the time of your comment, maybe the mirror you use didn't sync up to upstream at that time yet.

https://archlinux.org/packages/extra/x86_64/gnome-shell/

Last Updated: | 2023-10-09 20:00 UTC

**Comment by qwreey75** [comment]
![image](https://github.com/qwreey75/quick-settings-tweaks/assets/46598063/162ab4ae-ad45-476e-a608-97ec3638b1ad)
okey, i tested in 45 and working now... let's push release

**Comment by qwreey75** [comment]
![image](https://github.com/qwreey75/quick-settings-tweaks/assets/46598063/6446cbd3-27a7-49bd-b1f4-c0298a09465b)
waitting for review...

**Comment by freddyw** [comment]
Seems to work fine at first glance on Fedora 39 (Beta) . Thanks for the quick solution!!

**Comment by qwreey75** [comment]
![image](https://github.com/qwreey75/quick-settings-tweaks/assets/46598063/a6a5a9cd-9c00-444a-a20c-d6d3fbaf24a0)
+.. now it supports translation on pref page

**Comment by qwreey75** [comment]
![image](https://github.com/qwreey75/quick-settings-tweaks/assets/46598063/1fefc962-27b3-4b49-aecc-94f49e53e762)
![image](https://github.com/qwreey75/quick-settings-tweaks/assets/46598063/a64e2996-2092-45c8-a599-8f632ad46eed)

made the UI more intuitive

**Comment by befabry** [comment]
Thanks dude, one of my fav extension ! I don't have it yet on Gnome 45, but knowing it's coming is great !

**Comment by qwreey75** [comment]
![image](https://github.com/qwreey75/quick-settings-tweaks/assets/46598063/2eefcdc4-ca5e-4e04-b8aa-e9305c7a1f24)
![image](https://github.com/qwreey75/quick-settings-tweaks/assets/46598063/d1493245-20ff-4d15-a3e9-f6856bd147e6)
about panel redesign

Now good to release it!

**Comment by qwreey75** [comment]
![image](https://github.com/qwreey75/quick-settings-tweaks/assets/46598063/b4e06658-9ec8-49c9-9069-1c6014f7683c)
Released!
