### ISSUE TITLE
Long titled stream make modal larger

### ISSUE THREAD

**Issue by qwreey75** [qwreey75/quick-settings-tweaks#11]
title says everything
![image](https://user-images.githubusercontent.com/46598063/199556007-bca9eee9-172e-4012-8b47-092f4096c299.png)
![image](https://user-images.githubusercontent.com/46598063/199555606-8d83b543-e565-424f-9b82-1bdc1c03f033.png)

stream title text label should have this style prop 
text-overflow: ellipsis;

**Comment by DodoLeDev** [comment]
You could also edit the stream title text before showing it on the QS panel! You'll then gain the control of how the text will be displayed, and thus not having to rely on Gnome 43's QS panel behaviour, which, moreover, will be subject to modifications by the Gnome Team! :smiley:

**Comment by qwreey75** [comment]
![image](https://user-images.githubusercontent.com/46598063/200077541-2cb480d1-3b00-4da8-bfd8-3d1f9fcc14e2.png)

Image shows everything!
