### ISSUE TITLE
"QuickSettings._system is undefined" on GNOME 45

### ISSUE THREAD

**Issue by arngo** [qwreey75/quick-settings-tweaks#113]
On startup the extension fails to load with the error "QuickSettings._system is undefined". The error happens in libs/gnome.js on line 21.
In GNOME 45 quick settings menu items are added asynchronously and can be undefined when the extension loads. This post describes the same issue and has a code sample to help with a solution: https://discourse.gnome.org/t/main-panel-statusarea-quicksettings-system-is-undefined/16827/2

The same fix should also be used for lines 24 and 25 where `QuickSettings._volumeInput` and `QuickSettings._volumeInput` are used.

**Comment by qwreey75** [comment]
Fixed in https://github.com/qwreey75/quick-settings-tweaks/commit/8f76d00ad832cf63d69b154480e1c419263d1f03 and https://github.com/qwreey75/quick-settings-tweaks/commit/7b781c7b2217adde7c4469b33cee03635e2242ca
