### ISSUE TITLE
Gnome 45 is out not working

### ISSUE THREAD

**Issue by thor2002ro** [qwreey75/quick-settings-tweaks#114]
manjaro updated gnome to 45 broke almost every extension basically imports need to be rewritten and break compat with older versions

**Comment by qwreey75** [comment]
https://github.com/qwreey75/quick-settings-tweaks/issues/109

See

**Comment by qwreey75** [comment]
![image](https://github.com/qwreey75/quick-settings-tweaks/assets/46598063/47a20284-ca6d-4d6b-ba9c-12c2236d0d6c)
You can try 45 with master branch now

**Comment by thor2002ro** [comment]
yep seams to work :)
