### ISSUE TITLE
Avoid the use of stylesheet.css for media control or notification widget

### ISSUE THREAD

**Issue by dasnoopy** [qwreey75/quick-settings-tweaks#13]
Hi,  first of all, thanks in advance for the development of this amazing extension :-)

going straight to the point,  this is not a real issue  but maybe a feature request or something similar: 

So, to fit my needs, I  made a custom theme of Adwaita  gnome  shell theme mainly I changed colors and widget roundness

I noticed that your extension use a **stylesheet.css** file  that force  e.g roundness e.g of media control or notification widgets, presumably like the original adwaita gnome shell theme . 

Can this be avoided in some way? I mean can the media control or notification widget  adopt the same style of my custom theme?

Attached screenshot maybe describe better my request:

![screenshot](https://user-images.githubusercontent.com/296922/199604356-1739aae4-5041-4f0b-b70a-b335180e14ae.png)

Regards
Andrea

**Comment by qwreey75** [comment]
![Image](https://user-images.githubusercontent.com/46598063/200119284-bf77250c-873d-49c5-a501-5aff2819aa13.png)

![image](https://user-images.githubusercontent.com/46598063/200119322-fd325a8f-fd32-47bd-b5e4-5cd51ea90a46.png)

I will add more options in there! (padding, margin …) now you can disable border adjusting on settings

**Comment by dasnoopy** [comment]
Thank you so much to release v13,   that "solve" the issue... 
Again, great gnome 43 extension

Regards
