### ISSUE TITLE
Weird artifacts around the border

### ISSUE THREAD

**Issue by ItzYanick** [qwreey75/quick-settings-tweaks#18]
When using the extensions around the borders of the notifications and the media control are weird things. Kinda looks like shadows / or artifacts. I don't know how to describe them best.
![image](https://user-images.githubusercontent.com/18502828/199681603-d33ea1fa-784c-42f2-b2f1-ead8064aba5d.png)

**Comment by qwreey75** [comment]
Maybe `box-shadow: none` can fix this?
I don't know how to fix this issue...
But i will try to fix!

**Comment by ItzYanick** [comment]
So i added `box-shadow: none` to `.QSTWEAKS-media` and it appers to have fixed it for the media control part. I do not know where to add it for the notifications but yea it seems to fix it.

**Comment by qwreey75** [comment]
Thank you for checking how to fix
I will add option to add style 'box-shadow: none'!
~~I'm on GMT+8 timezone, that mean it's late night! And I need to sleep now for the next day. I will add this on next day. Sorry for late!~~

**Comment by qwreey75** [comment]
![image](https://user-images.githubusercontent.com/46598063/200330908-b640b168-955e-4d39-bc87-5353a8b69b9f.png)

I Added an option to remove shadow
Thanks for the good idea!

**Comment by ItzYanick** [comment]
So i tested the new version now for 2 days and haven't seen any bugs or problems so i will close this issue for now. Thanks for fixing it!
