### ISSUE TITLE
Integrated notifications: fading-effect bug with long list of notifications

### ISSUE THREAD

**Issue by Leleat** [qwreey75/quick-settings-tweaks#19]
![image](https://user-images.githubusercontent.com/53054301/199695905-23d3abea-5e13-49b1-a1f5-805ea5bdc925.png)

**Comment by Leleat** [comment]
It does appear to be related to the scrollbar. Changing the scrollbar's width to 0 will expand the fade effect. Adding `this.list.get_vscroll_bar().width = 0` to `notifications.js` will result in this

![image](https://user-images.githubusercontent.com/53054301/199954210-6a81a5cc-a260-4f76-8cf4-2c76bd56b732.png)

Downside is there is no scrollbar visible at all... although I think it actually looks good.

Do you want me to open a PR with this? Or do you want to try to find a different/proper fix? Maybe you can do something in css since that's how you also enlarged the messages...

**Comment by qwreey75** [comment]
I can't found that how to check when vscrollbar_visible of StScrollView will be change

// ... basic
list.vscroll.connect("hide")
 : not work, show too

// Checking by height
list.last_child.connect("notify::height")
 : not work

// Checking by property notify
list.connect("notify::vscrollbar_visible")
 : not work

// Checking by child add/remove event
list.last_child.first_child.first_child.connect("actor-added",()=>{Main.testt})
 : not work

And also, i can't found any useful information in https://gjs-docs.gnome.org/st10~1.0_api/st.scrollview
Did you know how to get event of 'vscrollbar_visible'?

**Comment by Leleat** [comment]
Hmm, this sounds like the cause/fix of this issue... ?

https://gitlab.gnome.org/GNOME/gnome-shell/-/merge_requests/2190/

**Comment by qwreey75** [comment]
![image](https://user-images.githubusercontent.com/46598063/235281416-24444e65-65c9-4ca6-a5c0-cdd1bfcc80e5.png)
![image](https://user-images.githubusercontent.com/46598063/235281473-b73b2f01-05dd-45c8-be3e-4d61ab517c71.png)

This bug was fixed on dev branch. now it toggles overlay_scrollbars property automatically!
