### ISSUE TITLE
Hide WiFi button

### ISSUE THREAD

**Issue by Anuskuss** [qwreey75/quick-settings-tweaks#25]
I disabled `NMWirelessToggle` and while it initially works, it "forgets" after reboot (the toggle remains on though).

**Comment by qwreey75** [comment]
It because this extension doesn't re-apply button hiding when system reloaded QS

I know this problem and I will add event listening on extension for fix

**Comment by qwreey75** [comment]
Maybe fixed in https://github.com/qwreey75/quick-settings-tweaks/releases/tag/1.13 ?
Can you check that newer version can fix your issue?
If everything ok, it's ok to close this issue!

* Note: But, some bugs still exist. eg) removing some sliders making modal bigger.

**Comment by Anuskuss** [comment]
Thanks, it works!
