### ISSUE TITLE
"Do not disturb" is missing.

### ISSUE THREAD

**Issue by 3laws** [qwreey75/quick-settings-tweaks#3]
Close if not applicable but I think this is missing a very essential feature of the notification panel.

I don't see any flag in the build files to make it an option, is this feature just missing or is my extension not working?

**Comment by andia89** [comment]
maybe one can add it as a quick-toggle button if the notifications are moved to the quick settings menu as well?

**Comment by qwreey75** [comment]
I missed adding, thank you for making me know this!
![image](https://user-images.githubusercontent.com/46598063/199064633-f3f0355f-d06b-4026-8ed9-f9c2e1db42c8.png)

![image](https://user-images.githubusercontent.com/46598063/199064902-28063d06-7a0e-43a1-a90f-270acd26acf1.png)
Now dnd button will be added as default (but you can disable too)

**Comment by andia89** [comment]
@qwreey75 Thanks that is great! However, there is a small issue. The DND button is only there once there is a notification present, i.e. I can only turn it on once I got a notification. Don't you think it would be better to add it as a quick-setting toggle (like airplane mode etc...), such that one can toggle it even without a notification present?

**Comment by qwreey75** [comment]
How about displaying "No notifications" text when having no notifications?
Or provide two options: Add QS Button/Add switch on bottom of notification box and add no notification text
i will try two options when i have break time! thank you for finding an uncatched issue

**Comment by qwreey75** [comment]
![image](https://user-images.githubusercontent.com/46598063/199298010-edee2420-b8b6-4d6a-9975-eb7f86e2923a.png)
Temporary fix?

I haven't found any API related to dnd yet as I'm busy this week, so i didn't make quick-toggle button now. But i will try it on weekend!
~~sorry for lack of english skill~~

**Comment by 3laws** [comment]
This last approach is 100% acceptable for most use cases and it doesn't stray away from the vanilla experience.

Thanks for taking the time to improve your extension even further, much much appreciate it! Whether or not [notifications are a different popup](https://github.com/qwreey75/quick-settings-tweaks/issues/8) is honestly I see it as up to you, would be nice for vertical space saving but it doesn't ruin the experience for me personally.
