### ISSUE TITLE
Settings don't persist when logging back in

### ISSUE THREAD

**Issue by dtcooper** [qwreey75/quick-settings-tweaks#30]
Hi there,

On Ubuntu 22.10 with gnome version 43.0, I configure quick settings Quick Settings Tweaker and everything works fine.

Then when I log out, and log back in, none of the changes persist. The only way to get my changes working again are to disable and re-enable Quick Settings Tweaker again. Thanks!

Note: settings that don't persist are "Button Remover" configuration.

**Comment by qwreey75** [comment]
This is a weird problem. Extension is can be loaded even system quick toggle isn't loaded.
I try to fix this, Added listening event, but it caused gnome-shell crash.

https://github.com/qwreey75/quick-settings-tweaks/issues/25
Same with

**Comment by qwreey75** [comment]
Maybe fixed in https://github.com/qwreey75/quick-settings-tweaks/releases/tag/1.13
> But, some bugs still exist. eg) removing some sliders making modal bigger.

Can you check that newer version can fix your issue?

**Comment by dtcooper** [comment]
It works!

One additional bug, when _everything_ is removed from the quick settings, including disabling "Volume Mixer"... if I click on the top right quick settings, GNOME completely crashes.

My use case: I'm trying to lock down GNOME superficially. For example, I don't want any users to be able to easy change things, lock the computer, etc... since it will be used in a live radio station.

If a user _really_ wants to make changes, they can search for them in the settings app, etc. But no naive clicks should be able to lock screen, log out, shut down, change volume or switch output device or anything like that.

My fix right now is to leave only `DarkModeToggle` enabled, since I don't care if a user changes from dark/night mode.
