### ISSUE TITLE
Application Filtering List won't add new items (Volume Mixer)

### ISSUE THREAD

**Issue by Iwaslazkis** [qwreey75/quick-settings-tweaks#32]
Hello,
So it seems that whenever I try to add an item to the Application Filtering list for the Volume Mixer feature, it simply refuses to add anything. Specifically, pressing the "+" icon shows the prompt to add a new application normally, but no matter what I type in there, once I press "Add" nothing happens; and the application continues to appear in the Volume Mixer. This happens both under the Block and Allow Filter modes, and I've even tried entering the direct path to applications or desktop entries, and it still doesn't work.
If makes any differences, I'm running Arch with Gnome 43.1 (though the Gnome version may have been obvious).

Please let me know if there's any logs or something I can provide you with, as I'd love to use the Volume Mixer feature if this gets fixed (otherwise my 15+ YouTube tabs that are always open make the Quick Settings menu unusably long...).

Oh, and while I'm here, I just wanted to let you know that this is an awesome extension! I greatly appreciate the level of customization it offers me, thanks for creating this. :)

**Comment by qwreey75** [comment]
Fixed in https://github.com/qwreey75/quick-settings-tweaks/releases/tag/1.13
Thank you for telling me!
