### ISSUE TITLE
gnome 43 the settings for this extension cannot be displayed

### ISSUE THREAD

**Issue by xevilstar** [qwreey75/quick-settings-tweaks#39]
Error: Wrong type number; string expected

Stack trace:
  _init/Gtk.Widget.prototype._init@resource:///org/gnome/gjs/modules/core/overrides/Gtk.js:55:50
  aboutPage@/home/xevilstar/.local/share/gnome-shell/extensions/quick-settings-tweaks@qwreey/prefPages/about.js:32:21
  fillPreferencesWindow@/home/xevilstar/.local/share/gnome-shell/extensions/quick-settings-tweaks@qwreey/prefs.js:18:20
  _init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:27:29
  ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:10:4
  OpenExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:124:33
  async*_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:368:35
  _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:401:34
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:186:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:22:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17

**Comment by rivenirvana** [comment]
See Issue #37, fixed in #38

**Comment by xevilstar** [comment]
latest git just cloned make make install restarted session ....

Error: GSettings key user-removed-buttons not found in schema org.gnome.shell.extensions.quick-settings-tweaks

Stack trace:
  _checkKey@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:732:23
  createCheckedMethod/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:684:30
  quickTogglesPage@/home/xevilstar/.local/share/gnome-shell/extensions/quick-settings-tweaks@qwreey/prefPages/quickToggles.js:57:39
  fillPreferencesWindow@/home/xevilstar/.local/share/gnome-shell/extensions/quick-settings-tweaks@qwreey/prefs.js:18:20
  _init@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:27:29
  ExtensionPrefsDialog@resource:///org/gnome/Shell/Extensions/js/extensionPrefsDialog.js:10:4
  OpenExtensionPrefsAsync@resource:///org/gnome/Shell/Extensions/js/extensionsService.js:124:33
  async*_handleMethodCall@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:368:35
  _wrapJSObject/<@resource:///org/gnome/gjs/modules/core/overrides/Gio.js:401:34
  run@resource:///org/gnome/Shell/Extensions/js/dbusService.js:186:20
  main@resource:///org/gnome/Shell/Extensions/js/main.js:22:13
  run@resource:///org/gnome/gjs/modules/script/package.js:206:19
  start@resource:///org/gnome/gjs/modules/script/package.js:190:8
  @/usr/share/gnome-shell/org.gnome.Shell.Extensions:1:17

**Comment by qwreey75** [comment]
![Screenshot_20221107-180730_Chrome](https://user-images.githubusercontent.com/46598063/200271156-5b98996c-2fe8-47d4-8f22-c314cc558699.jpg)
? w..what

**Comment by xevilstar** [comment]
![settings](https://user-images.githubusercontent.com/1389525/200274896-8ca55fb0-b17d-41aa-86be-7184f10bdb1c.png)

**Comment by rivenirvana** [comment]
Needs a `"version"` key in `metadata.json`.

**Comment by qwreey75** [comment]
> Needs a `"version"` key in `metadata.json`.

Version key automately generated when uploading extension on gnome-extension. And we can't add version key on metadata manually

That mean, when we build extension manually. The value 'version' is undefined

**Comment by xevilstar** [comment]
issue fixed
