### ISSUE TITLE
How to move Notifications to the Bottom?

### ISSUE THREAD

**Issue by Khraut** [qwreey75/quick-settings-tweaks#44]
I have an weird issue with the extension. The Notification Panel is placed above the Quicksettings-Panel.
To me, this is very annoying because there is no fixed position for the Settings-Panel. Is there an option I'm missing? 

Everything else is working so far, thank you for this nice Project!

**Comment by qwreey75** [comment]
![image](https://user-images.githubusercontent.com/46598063/201349135-83cc3c5b-ff36-4d70-930d-3bb44623892c.png)
I checked that Option 'Put above QS Panel' was removed in some commit
Idk why that option was removed. but i will restore it on next release! sorry for this mistake

**Comment by qwreey75** [comment]
![image](https://user-images.githubusercontent.com/46598063/201351688-7f86047f-8e2e-4278-bde9-320df10a908a.png)
Now we can select where notification widget should be put!

**Comment by Khraut** [comment]
Thank you very much, now I can select the position to my needs! I think this is solved.
