### ISSUE TITLE
Disabling quick toggles only works on main screen

### ISSUE THREAD

**Issue by julienfalque** [qwreey75/quick-settings-tweaks#61]
I have a laptop connected to an external monitor. The internal display of the laptop is disabled as I only use the external one so the external one is the main display. The extension works great on the menu on this monitor. But sometimes I also need to enable the internal display. When I do, the quick toggles I removed on the main screen are all visible on the laptop screen. I use Dash to Panel extension to have the panel on all screens.

**Comment by KarolWojtasiuk** [comment]
I have a similar issue, I use "Dash To Panel" extension to have panels on two monitors and this extension only changes quick settings on primary display

**Comment by qwreey75** [comment]
duplicated wich #54, secondary monitor will be not supported due to a technical issue
