### ISSUE TITLE
After suspending session, output chooser no longer presents list of available output device

### ISSUE THREAD

**Issue by greenaussie** [qwreey75/quick-settings-tweaks#68]
Fedora 37 / Wayland / Pipewire

Resuming after suspending Gnome 43 session, output chooser no longer presents list of available output devices. With Wayland, it is necessary to log out and then back in again. Stopping and starting the extension (or all extensions) is not sufficient. 

Before suspend:
![Before suspend](https://greenaussie.github.io/github_pages_public_files/a88b7f12-3246-47a9-8ab0-b8b17d75268f/before-suspend.png)

After suspend:
![After suspend](https://greenaussie.github.io/github_pages_public_files/a88b7f12-3246-47a9-8ab0-b8b17d75268f/after-suspend.png)

**Comment by greenaussie** [comment]
A little more info - adding a new audio output device (e.g. connecting my bluetooth headphones) results in the options menu returning - however it does not show the full list of devices which are available - it shows the previously selected device, and the availability of the newly added device:

![after-new-device-added-still-missing-some.png](https://greenaussie.github.io/github_pages_public_files/a88b7f12-3246-47a9-8ab0-b8b17d75268f/after-new-device-added-still-missing-some.png)

Selecting an unlisted device from the Gnome settings Panel doesn't bring it into the Quick Settings tweaks list.

**Comment by qwreey75** [comment]
QSTweak doesn't touch the device selector.
Maybe pipewire/pulseaudio bug? I can't reproduce this issue on pulseaudio. and this bug can be a gnome issue, can you check pulsemixer if you use pulseaudio? 
![image](https://user-images.githubusercontent.com/46598063/234881881-01fcc2fe-db5a-4d8f-9786-b0c04f6bf7a3.png)
Every device should displayed in here

**Comment by greenaussie** [comment]
I'll accept your suggestion the bug may have lived elsewhere, as following some updates (I'd assumed yours but perhaps not), the effect is no longer present. Thanks for looking to this. Closing.

**Comment by frandmb** [comment]
Having this exact same issue on Gnome 43.2, x11. Installed from Gnome Extensions
Both pavucontrol and Gnome settings show the devices, I actually need to select them from here or refresh the session (alt+f2 then "r") for the devices to appear again on the extension, or to manually reconnect them.
Any idea on what could be causing this or an idea to debug it?
