### ISSUE TITLE
Extension changes quick toggle menu size

### ISSUE THREAD

**Issue by Leleat** [qwreey75/quick-settings-tweaks#7]
Here is a screenshot with the extension disabled (left) and the extension enabled (right)

![scr](https://user-images.githubusercontent.com/53054301/199230317-116cfd21-afeb-41f7-8f9d-63750a1002dc.png)

**Comment by qwreey75** [comment]
![image](https://user-images.githubusercontent.com/46598063/199243730-c5c44aea-e6e9-4900-aa92-3feebd637eb6.png)

**Comment by qwreey75** [comment]
> Sorry, don't understand why you posted the screenshot. I can see the same issue in your image.

Sorry for too late reply; it just mean i checked this issue too

quick-toggle-menu-container's parent is not QuickSettings.menu.box but QuickSettings.menu.actor
that means actor should have margin too. and i added margin on actor. result is below

![image](https://user-images.githubusercontent.com/46598063/199271192-e67797f8-a032-4839-b669-c0f99cbe771a.png)

Maybe fixed?
I will push new version

**Comment by Leleat** [comment]
Ah I see, thanks 👍. It does appear fixed in the screenshot. Should I close this issue?
