### ISSUE TITLE
Integrate notifications into the main quick settings popup

### ISSUE THREAD

**Issue by Leleat** [qwreey75/quick-settings-tweaks#8]
Don't know if there is a reason why the notifications are in a separate popup (maybe so that you could move it above the main popup?). But I think it would look better if notifications were integrated into the main popup. There is an older GNOME mockup, which I think looks quite nice https://gitlab.gnome.org/Teams/Design/os-mockups/-/blob/master/system-status/quick-settings/quick-toggles-2.png

PS. a setting to move the notification position would be pretty good as well since it's kinda weird that notifications popup in the center but then end up being listed in the quick settings menu on the right. Although there are a few extensions which do that already e. g. `just-perfection`. So don't know if it's really needed...

**Comment by qwreey75** [comment]
separate popup make [weird visual issue too](https://github.com/qwreey75/quick-settings-tweaks/issues/7)

Actually, separated popup is made in very weird way (removing style_class, adding style_class on qs box/actor ...)
it breaks theme system, so it seemed weird for some themes
So, i think Integrate notifications is better than separated one too, i will try to implement!

i think moving notification popup position is pretty good function, but i can't prevent crash with just-perfection now

**Comment by qwreey75** [comment]
![image](https://user-images.githubusercontent.com/46598063/199297076-a4fe3eff-5d16-47cb-87dd-ecd96b7eab45.png)
![image](https://user-images.githubusercontent.com/46598063/199297189-bf123ffd-f107-426f-854c-fb485c84c30c.png)

Maybe better? 🤔

**Comment by Leleat** [comment]
> Maybe better? :thinking:

I would say so. Here is how it looks on Fedora (with the default shell theme). I like it better 😃

![scr3](https://user-images.githubusercontent.com/53054301/199338458-4124aa36-eebf-45c9-9903-aa1502685de2.png)

I did notice one bug. When there are a lot of notifications, the fading overlay doesn't span the entire notification. Here is a screenshot

![scr](https://user-images.githubusercontent.com/53054301/199338738-bb6d7bbf-9c65-4e39-94c7-3259efdfb676.png)

---

And maybe some suggestions you may consider:

- if the notifications (and the DND button) are moved to the quick settings, I think it makes sense to also move the DND bell from the date menu to the system status area. I am talking about this bell

![scr2](https://user-images.githubusercontent.com/53054301/199339567-53328c76-76a3-49e0-81cf-7b9eb006f156.png)

- the text `Notifications` probably should be bold since it's a title
- Instead of just text (`No Notifications`) a 'placeholder page' (see [GNOME's HIG](https://developer.gnome.org/hig/patterns/feedback/placeholders.html?highlight=empty%20state)) might look prettier. You could probably just copy GNOME's current one (just smaller)

![scr4](https://user-images.githubusercontent.com/53054301/199341054-7ee886df-c60d-4ee7-a3f0-efa599648ee7.png)

- the DND toggle (text+button) looks a bit weird down there. Those should probably be replaced with a DND quick toggle. That's more in line with GNOME's mockup and modern phone quick settings. I think that's also asked for in https://github.com/qwreey75/quick-settings-tweaks/issues/3

PS. Sorry for the long post 😅

**Comment by Leleat** [comment]
Do you accepts PRs? I implemented some stuff on a local copy and I could open a PR. For example: the DND QuickToggle and a placeholder page

![scr2](https://user-images.githubusercontent.com/53054301/199597484-41bd623f-b13c-4435-a920-cece9252e394.png)
![scr1](https://user-images.githubusercontent.com/53054301/199597475-25545b40-dfd6-4e58-94cc-b02de9cf522d.png)

**Comment by qwreey75** [comment]
> Do you accepts PRs?
Sure! Your new implement looks great!

**Comment by Leleat** [comment]
> Sure! Your new implement looks great!

Alright. I am closing this then since the main issue has already landed in `master`. I'll open a new issue for the bug and PRs for my suggestions.
