### ISSUE TITLE
Will be there GNOME 44 Support?

### ISSUE THREAD

**Issue by kanansnote** [qwreey75/quick-settings-tweaks#84]
Hello there. There's a still opening [issue](https://github.com/qwreey75/quick-settings-tweaks/issues/71) like a month ago, so I was wondering if that was going to be added soon. Thanks.

**Comment by qwreey75** [comment]
Yes, in dev branch, should everything works fine. I'll update the extension ASAP
If you wonder dev status, checkout #81 !
