### ISSUE TITLE
label for notification missing (gnome 44.1)

### ISSUE THREAD

**Issue by Neo-29** [qwreey75/quick-settings-tweaks#89]
Just the Icon, no text .
Something is missing for gnome 44.1

**Comment by gmankab** [comment]
![image](https://github.com/qwreey75/quick-settings-tweaks/assets/73340745/958f8461-951e-4a69-8512-a397772766fb)

same problem

**Comment by Neo-29** [comment]
> ![image](https://user-images.githubusercontent.com/73340745/239716251-958f8461-951e-4a69-8512-a397772766fb.png)
> 
> same problem

And nobody cares 🤣🤣😝

**Comment by gmankab** [comment]
it fixed now

**Comment by Neo-29** [comment]
> it fixed now

Yeahhh.... By chance I tried yesterday and saw that!
Good work
