### ISSUE TITLE
Install script doesn't work on Wayland

### ISSUE THREAD

**Issue by Leleat** [qwreey75/quick-settings-tweaks#9]
https://github.com/qwreey75/quick-settings-tweaks/blob/1589517a6552351a823ec119c789749465db130d/install.sh#L5

Killing gnome-shell only works on Xorg. If gnome-shell crashes on Wayland , it will take down everything and the user will end up back at the login screen. That means they may end up losing unsaved work.

Unfortunately, there isnt a good way to initiliaze/enable an extension with a script on Wayland. Users need to log out and back in again.

**Comment by qwreey75** [comment]
This script is made for convenience of development. i think just rename install.sh into dev_reload.sh and add new install.sh script is way to solve this issue. I will apply this changes!

**Comment by Leleat** [comment]
> This script is made for convenience of development.

Ah I see, my bad. Closing this then.
